#!/bin/sh

quiet=${quiet:-${1:-0}}
project=${project:-${2:-"nuvlabox"}}

nuvlabox-engine-printer "Uninstalling NuvlaBox Engine - ${project} - (permanently)" ${quiet} "NONE" yes

docker_compose_command="docker-compose --ansi never --log-level ERROR -p ${project} down -v --remove-orphans"

nuvlabox-engine-printer "Executing uninstall command: ${docker_compose_command}" ${quiet} "INFO" "no"

if [[ ${quiet} -eq 1 ]]
then
  out=$($docker_compose_command 2>&1)
else
  out="\n$($docker_compose_command)"
fi

if [[ $? -ne 0 ]]
then
  nuvlabox-engine-printer "Uninstall didn't work.${out}" 0 "WARNING" "no"
  nuvlabox-engine-printer "Trying to uninstall a second time..." 0 "INFO" "no"
  if [[ ${quiet} -eq 1 ]]
  then
    out=$($docker_compose_command 2>&1)
  else
    out="\n$($docker_compose_command)"
  fi
  if [[ $? -ne 0 ]]
  then
    nuvlabox-engine-printer "Uninstall failed when executing Docker Compose command ${docker_compose_command}.${out}" 0 "ERROR" "no"
    exit 1
  fi
fi

# if we got here, then install was successful
nuvlabox-engine-printer "NuvlaBox Engine uninstalled successfully!" 0 "" "no"