#!/usr/bin/env python3

"""Used when installing a new NuvlaBox Engine

After a successful installation, it waits in foreground
until it receives a shutdown signal.
When that happens, it launches an uninstall process to
remove the ongoing NuvlaBox Engine
"""

import docker
import sys
import socket

project_name = sys.argv[1]

dc = docker.from_env()

myself = dc.containers.get(socket.gethostname())

my_image_id = myself.image.id

print('Uninstalling the NuvlaBox Engine')
docker.from_env().containers.run(my_image_id,
                                    name="nuvlabox-engine-uninstaller",
                                    remove=True,
                                    volumes={
                                        '/var/run/docker.sock': {
                                            'bind': '/var/run/docker.sock',
                                            'mode': 'ro'
                                        }
                                    },
                                    detach=True,
                                    command=["uninstall", "--project=" + project_name])
