#!/bin/sh

compose_files=${compose_files:-$1}
target_version=${target_version:-$2}
quiet=${quiet:-${3:-0}}
on_update_failure=${on_update_failure:-$4}
environment=${environment:-$5}
project=${project:-$6}
github_releases=${github_releases:-${7:-"https://github.com/nuvlabox/deployment/releases"}}
force_restart=${force_restart:-${8:-0}}
working_dir=${working_dir:-$9}
current_version=${current_version:-${10}}
hard_reset=${hard_reset:-0}

nuvlabox-engine-printer "Updating NuvlaBox Engine to version ${target_version}" ${quiet} "NONE" yes

if [[ -z ${project} ]]
then
  nuvlabox-engine-printer "Update failed! Cannot update without a project name." 0 "ERROR" "no"
  exit 1
fi

if [[ ! -z "${environment}" ]]
then
  env_file="${working_dir}/.env"
  nuvlabox-engine-printer "Setting environment for update, at ${env_file}" ${quiet} "INFO" "no"

  env_lines=$(echo ${environment} | sed 's/,/\\n/g')
  nuvlabox-engine-printer "New environment variables:\n${env_lines}" ${quiet} "DEBUG" "no"

  echo -e "${env_lines}" | grep -v "affinity:container" > ${env_file}

  if [[ $? -ne 0 ]]
  then
    nuvlabox-engine-printer "Update failed! Unable to store enviroment ${env_lines} in ${env_file}." 0 "ERROR" "no"
    exit 1
  fi
fi

source_code_url="${github_releases}/download/${target_version}"

nuvlabox-engine-printer "Downloading config files ${compose_files} from ${source_code_url}" ${quiet} "INFO" "no"

download=$(nuvlabox-engine-download-configs "${compose_files}" "${working_dir}" "${source_code_url}" 2>&1)

if [[ $? -ne 0 ]]
then
  nuvlabox-engine-printer "Update failed! Unable to retrieve files ${compose_files}: ${download}" 0 "ERROR" "no"
  exit 1
fi

nuvlabox-engine-printer "Preparing to update NuvlaBox Engine running as project ${project}" ${quiet} "NONE" "yes"

docker_compose_args=$(echo "-f $(echo ${compose_files} | sed 's/,/ -f /g')")

if [[ ${force_restart} -eq 1 ]]
then
  # when doing a "down" it is better to use the original compose files
  if [[ ! -z ${current_version} ]]
  then
    down_dir="/tmp/down"
    mkdir -p ${down_dir}
    source_code_url_current="${github_releases}/download/${current_version}"

    nuvlabox-engine-printer "Downloading current config files ${compose_files} from ${source_code_url} for shutdown" ${quiet} "INFO" "no"

    download=$(nuvlabox-engine-download-configs "${compose_files}" "${down_dir}" "${source_code_url_current}" 2>&1)

    if [[ $? -ne 0 ]]
    then
      nuvlabox-engine-printer "Failed to retrieve current files ${compose_files} for shutdown: ${download}" 0 "ERROR" "no"
      cd ${working_dir}
    else
      cd ${down_dir}
    fi
  fi

  docker_compose_down_command="docker-compose --ansi never --log-level ERROR -p ${project} ${docker_compose_args} down --remove-orphans"

  if [[ ${hard_reset} -eq 0 ]]
  then
    nuvlabox-engine-printer "Forcing the restart of the NuvlaBox Engine components before updating" ${quiet} "WARNING" "no"
    delete_volume=0
  else
    nuvlabox-engine-printer "Forcing the hard reset (full re-installation) of the NuvlaBox Engine components before updating" ${quiet} "WARNING" "no"
    docker_compose_down_command="${docker_compose_down_command} -v"
    delete_volume=1
  fi

  echo ${hard_reset} ${docker_compose_down_command}
  nuvlabox-engine-printer "Executing 'down' command: ${docker_compose_down_command}" ${quiet} "WARNING" "no"

  if [[ ${quiet} -eq 1 ]]
  then
    out=$($docker_compose_down_command 2>&1)
  else
    out="\n$($docker_compose_down_command)"
  fi

  if [[ $? -ne 0 ]]
  then
    nuvlabox-engine-printer "Force restart failed (trying again): ${out}" ${quiet} "WARNING" "no"
    if [[ ${quiet} -eq 1 ]]
    then
      out=$(nuvlabox-engine-force-cleanup "${project}" "${working_dir}" $delete_volume 2>&1)
    else
      out="\n$(nuvlabox-engine-force-cleanup "${project}" "${working_dir}" $delete_volume)"
    fi

    if [[ $? -ne 0 ]]
    then
      nuvlabox-engine-printer "Unable to force restart during update. Continue anyway - ${out}" ${quiet} "ERROR" "no"
    fi
  fi
fi

docker_compose_command="docker-compose --ansi never --log-level ERROR -p ${project} ${docker_compose_args} up --remove-orphans -d"

cd ${working_dir}

nuvlabox-engine-printer "Executing update command: ${docker_compose_command}" ${quiet} "INFO" "no"

if [[ ${quiet} -eq 1 ]]
then
  out=$($docker_compose_command 2>&1)
else
  out="\n$($docker_compose_command)"
fi

if [[ $? -ne 0 ]]
then
  nuvlabox-engine-printer "Update failed when executing Docker Compose command ${docker_compose_command}.${out}" 0 "ERROR" "no"
  exit 1
fi

wait=5
nuvlabox-engine-printer "Waiting ${wait} seconds and then checking updated NuvlaBox Engine health..." ${quiet} "INFO" "no"
sleep ${wait}

# set timeout for 60 seconds
timer=60
nuvlabox-engine-printer "Checking NuvlaBox Engine health (will timeout after ${timer} sec)..." ${quiet} "INFO" "no"
health=$(nuvlabox-engine-check-health ${timer} 2>&1)

if [[ $? -ne 0 ]]
then
  nuvlabox-engine-printer "Updated NuvlaBox Engine is not healthy. Updated failed with: ${health}" 0 "ERROR" "no"
  exit 1
fi

# if we got here, then update was successful
nuvlabox-engine-printer "NuvlaBox Engine update to version ${target_version} was successful!" 0 "" "no"