version: '3.3'

services:
  traefik:
    image: traefik:v2.9
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    configs:
      - source: traefik.yaml-1
        target: /traefik.yaml
      - source: dynamic.yaml-1
        target: /dynamic.yaml
    secrets:
      - source: nuvla.crt
        target: /nuvla.crt
      - source: nuvla.key
        target: /nuvla.key
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    deploy:
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
    networks:
      - traefik-public

configs:
  traefik.yaml-1:
    file: ./traefik/traefik.yaml
  dynamic.yaml-1:
    file: ./traefik/dynamic.yaml

secrets:
  nuvla.crt:
    file: ./secrets/nuvla.crt
  nuvla.key:
    file: ./secrets/nuvla.key

networks:
  traefik-public:
    external: true
