version: '3.3'

services:
  traefik:
    image: traefik:v2.8
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    configs:
      - source: traefik.yaml
        target: /traefik.yaml
    secrets:
      - source: nuvla.crt
        target: /nuvla.crt
      - source: nuvla.key
        target: /nuvla.key
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    deploy:
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
    networks:
      - traefik-public

configs:
  traefik.yaml:
    file: ./traefik/traefik.yaml

secrets:
  nuvla.crt:
    file: ./secrets/nuvla.crt
  nuvla.key:
    file: ./secrets/nuvla.key

networks:
  traefik-public:
    external: true
