version: '3.7'

services:
  traefik:
    image: traefik:v3.3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - lets-encrypt:/lets-encrypt
    configs:
      - source: traefik.yaml-1
        target: /traefik.yaml
      - source: dynamic.yaml-1
        target: /dynamic.yaml
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    deploy:
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
    networks:
      - traefik-public

volumes:
  lets-encrypt:
    driver: local

configs:
  traefik.yaml-1:
    file: ./traefik/traefik.yaml
  dynamic.yaml-1:
    file: ./traefik/dynamic.yaml

networks:
  traefik-public:
    external: true

