#!/bin/sh

#$1 - message
#$2 - print to file output.log (1/0)
#$3 - level (INFO, WARNING, DEBUG, ERROR). To avoid level prefix, pass empty string
#$4 - header (yes/no)

message="${1}"
to_file=${2:-0}
level=${3}
is_header=${4}

if [[ "${is_header}" == "yes" ]]
then
  message=" == ${message} == "
fi

#default_color=$'\e[1;39m'
#case ${level} in
#    INFO)
#      color=$'\e[1;36m';
#      ;;
#    WARNING)
#      color=$'\e[1;33m';
#      ;;
#    DEBUG)
#      color=$'\e[1;37m';
#      ;;
#    ERROR)
#      color=$'\e[1;31m';
#      ;;
#    *)
#      color=${default_color};
#      unset level
#      ;;
#esac

#color_end=$'\e[0m'

#if [[ "${level}" == "NONE" ]]
#then
#  unset level
#fi

if [[ ! -z ${level} ]]
then
  level="${level}: "
fi

if [[ ${to_file} -eq 1 ]]
then
  echo -e "${level}${message}" >> "${WORKDIR}/output.log"
else
  echo -e "${level}${message}"
fi