providers:
  docker:
    exposedByDefault: false
    swarmMode: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: ":443"
    http:
      middlewares:
        traefik-compress:
          compress:

api:
  dashboard: true
  insecure: true

log:
  level: DEBUG

accessLog: {}
