http:
  routers:
    catchall:
      # attached only to web entryPoint
      entryPoints:
        - "websecure"
      # catchall rule
      rule: "PathPrefix(`/`)"
      service: unavailable
      tls: {}
      # lowest possible priority
      # evaluated when no other router is matched
      priority: 1

  services:
    # Service that will always answer a 503 Service Unavailable response
    unavailable:
      loadBalancer:
        servers: {}

