providers:
  swarm:
    endpoint: "unix:///var/run/docker.sock"
    network: traefik-public
    exposedByDefault: false
    allowEmptyServices: true
  file:
    filename: dynamic.yaml

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: ":443"
    http:
      middlewares:
        traefik-compress:
          compress:

log:
  level: INFO

certificatesResolvers:
  cert-resolver:
    acme:
      email: foobar@example.com
      storage: /lets-encrypt/acme.json
      httpChallenge:
        entryPoint: web

metrics:
  prometheus: {}
