#!/usr/bin/env python3

"""Used when installing a new NuvlaEdge Engine

After a successful installation, it launches an uninstall process to
remove the ongoing NuvlaEdge Engine
"""

import docker
import os
import sys
import socket

project_name = sys.argv[1]

dc = docker.from_env()

myself = dc.containers.get(socket.gethostname())

my_image_id = myself.image.id

print('Uninstalling the NuvlaEdge Engine')
try:
    docker.from_env().api.remove_container("nuvlaedge-engine-uninstaller", force=True)
except:
    pass

docker.from_env().containers.run(my_image_id,
                                    name="nuvlaedge-engine-uninstaller",
                                    environment=[f"working_dir={os.getenv('working_dir')}"],
                                    remove=True,
                                    volumes={
                                        '/var/run/docker.sock': {
                                            'bind': '/var/run/docker.sock',
                                            'mode': 'ro'
                                        }
                                    },
                                    detach=True,
                                    command=["uninstall", "--project=" + project_name])
